import Link from "next/link";

export const metadata = { title: "Privacy Policy — CodeFounder" };

export default function PrivacyPage() {
  return (
    <div style={{ background: "#0a0a0a", minHeight: "100vh", color: "#e5e7eb", fontFamily: "'Plus Jakarta Sans', sans-serif" }}>
      <div style={{ maxWidth: 780, margin: "0 auto", padding: "60px 24px 80px" }}>

        {/* Back link */}
        <Link href="/" style={{ color: "#f97316", textDecoration: "none", fontSize: 14 }}>
          ← Back to CodeFounder
        </Link>

        <h1 style={{ fontFamily: "'Outfit', sans-serif", fontSize: 36, fontWeight: 800, color: "#fff", marginTop: 32, marginBottom: 6 }}>
          Privacy Policy
        </h1>
        <p style={{ fontSize: 13, color: "#6b7280", marginBottom: 40 }}>
          CodeFounder.ai (Viable Link Inc.) — Last updated June 2026
        </p>

        <div style={{ fontSize: 15, lineHeight: 1.8, color: "#d1d5db" }}>
          <p>
            This Privacy Policy describes how CodeFounder.ai, operated by Viable Link Inc. (&ldquo;CodeFounder&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;), collects, uses, and protects personal information when you use our website and SaaS platform.
          </p>

          <Section title="1. Information We Collect">
            <p>We collect information you provide directly when you register an account, submit a form, or subscribe to a plan:</p>
            <ul>
              <li><strong>Identity &amp; contact:</strong> name, email address, business name, phone number.</li>
              <li><strong>Billing information:</strong> processed securely through Stripe — we never store raw card numbers.</li>
              <li><strong>AI agent &amp; call data:</strong> call logs, transcripts, recording URLs, caller phone numbers, and call duration generated by your deployed voice agents.</li>
              <li><strong>Usage data:</strong> IP address, browser type, pages visited, referral URL, and session metadata collected for security and performance.</li>
            </ul>
          </Section>

          <Section title="2. How We Use Your Information">
            <ul>
              <li>Deliver and operate the services you have requested.</li>
              <li>Process payments and manage your subscription.</li>
              <li>Send transactional emails (account confirmation, invoices, service alerts).</li>
              <li>Improve our platform features and user experience.</li>
              <li>Detect, prevent, and investigate fraud or security incidents.</li>
              <li>Comply with legal obligations.</li>
            </ul>
            <p>We do not sell your personal data to third parties.</p>
          </Section>

          <Section title="3. Third-Party Services">
            <p>Our platform integrates with the following third-party providers who may process your data as sub-processors:</p>
            <ul>
              <li><strong>Vapi</strong> — voice AI infrastructure; processes call audio and transcripts.</li>
              <li><strong>Twilio</strong> — telephony services; handles inbound/outbound call routing.</li>
              <li><strong>Stripe</strong> — payment processing; handles billing under its own PCI-DSS compliance.</li>
              <li><strong>Supabase</strong> — database and authentication; stores account and call log data.</li>
              <li><strong>Google</strong> — analytics and workspace integrations.</li>
              <li><strong>Vercel</strong> — hosting infrastructure.</li>
            </ul>
            <p>Each provider is bound by data processing agreements and may only use your data to deliver the contracted services.</p>
          </Section>

          <Section title="4. Cookies and Analytics">
            <p>We use cookies to maintain session state and analyze site traffic via Google Analytics. Analytics data is collected in anonymized or pseudonymized form where possible. You can disable cookies in your browser settings; some platform features may require cookies to function.</p>
          </Section>

          <Section title="5. AI Agent Usage Data">
            <p>Inputs and outputs generated through your AI agents (call transcripts, messages, voice data) are used solely to deliver the requested functionality and are stored in your account. We do not use your client&apos;s data to train or fine-tune AI models for third-party purposes. Data is processed in accordance with applicable privacy law.</p>
          </Section>

          <Section title="6. Data Retention">
            <p>We retain your account data for as long as your account is active or as needed to fulfill the purposes described in this policy. Call logs and transcripts are retained for 12 months by default unless you request earlier deletion. When data is no longer required, it is securely deleted.</p>
          </Section>

          <Section title="7. Your Rights">
            <p>Depending on your jurisdiction, you may have the right to:</p>
            <ul>
              <li>Access a copy of the personal data we hold about you.</li>
              <li>Correct inaccurate or incomplete data.</li>
              <li>Request deletion of your personal data.</li>
              <li>Restrict or object to certain processing activities.</li>
              <li>Data portability (receive your data in a structured, machine-readable format).</li>
            </ul>
            <p>To exercise any of these rights, contact us at <a href="mailto:info@codefounder.ai" style={{ color: "#f97316" }}>info@codefounder.ai</a>.</p>
          </Section>

          <Section title="8. Security">
            <p>We implement industry-standard technical and organizational measures including encryption at rest and in transit, access controls, and regular security reviews. No method of transmission over the internet is 100% secure; we do our best to protect your information and will notify you of any breach as required by law.</p>
          </Section>

          <Section title="9. Changes to This Policy">
            <p>We may update this Privacy Policy periodically. Material changes will be communicated via email or an in-app notice at least 14 days before taking effect. Continued use of our services after the effective date constitutes acceptance of the updated policy.</p>
          </Section>

          <Section title="10. Contact">
            <p>
              Questions or requests? Contact us at{" "}
              <a href="mailto:info@codefounder.ai" style={{ color: "#f97316" }}>info@codefounder.ai</a>
              {" "}— Viable Link Inc., Kitchener, Ontario, Canada.
            </p>
          </Section>
        </div>

        <div style={{ marginTop: 56, paddingTop: 32, borderTop: "1px solid #1f2937", fontSize: 13, color: "#4b5563", display: "flex", gap: 24, flexWrap: "wrap" }}>
          <Link href="/terms" style={{ color: "#6b7280", textDecoration: "underline" }}>Terms of Service</Link>
          <Link href="/acceptable-use" style={{ color: "#6b7280", textDecoration: "underline" }}>Acceptable Use Policy</Link>
          <Link href="/" style={{ color: "#6b7280", textDecoration: "underline" }}>Home</Link>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginTop: 32 }}>
      <h2 style={{ fontFamily: "'Outfit', sans-serif", fontSize: 18, fontWeight: 700, color: "#fff", marginBottom: 10 }}>
        {title}
      </h2>
      {children}
    </div>
  );
}
